SELECT
    employees.employee_id,
    employees.first_name,
    employees.last_name,
    employees.email,
    employees.phone_number,
    employees.hire_date,
    employees.job_id,
    employees.salary,
    employees.commission_pct
FROM
    employees